spring:
  datasource:
    url: jdbc:mysql://localhost:3306/device_management?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 13098459921wct
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      host: localhost
      port: 6379
      database: 0
  mail:
    host: smtp.qq.com
    port: 587
    username: noreply@example.com
    password: change-me
